"""Alembic environment.

The URL comes from the application's own settings rather than alembic.ini, so
`alembic upgrade head` can never run against a different database than the one
the app is about to open. Importing `app.models` is what gives autogenerate a
complete target — every table must be reachable from `Base.metadata`.
"""
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app import models  # noqa: F401 — imported for its side effect: registering every table on Base
from app.db import Base, database_url

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", database_url().replace("%", "%%"))

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # SQLite cannot ALTER most column properties in place; batch mode makes
        # Alembic emit the create-copy-swap dance instead. Harmless on
        # PostgreSQL, and it means one migration script works on both.
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            # Type changes are not autogenerated by default; comparing them
            # surfaces a real drift between models and schema rather than
            # silently leaving the database with the old column type.
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
