"""v2 baseline schema

Revision ID: b64151666283
Revises: 
Create Date: 2026-09-08 23:22:49.546243
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b64151666283'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camera_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('ai_person', sa.Boolean(), nullable=True),
    sa.Column('ai_vehicle', sa.Boolean(), nullable=True),
    sa.Column('ai_anpr', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_frame_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('external_catalog_id', sa.String(), nullable=True),
    sa.Column('catalog_codec', sa.String(), nullable=True),
    sa.Column('catalog_live_status', sa.String(), nullable=True),
    sa.Column('catalog_synced_at', sa.DateTime(), nullable=True),
    sa.Column('catalog_stale', sa.Boolean(), nullable=True),
    sa.Column('whep_url', sa.String(), nullable=True),
    sa.Column('hls_url', sa.String(), nullable=True),
    sa.Column('camera_group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_code')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_external_catalog_id'), ['external_catalog_id'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('watchlist_flag', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plate_text', sa.String(), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('watchlist_flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_plate_text'), ['plate_text'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('cls', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('appearance_signature', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_track_id'), ['track_id'], unique=False)

    op.create_table('self_heal_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('recovery_action', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('self_heal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_self_heal_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_self_heal_events_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_self_heal_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('cls', sa.String(), nullable=False),
    sa.Column('yolo_track_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('plate_reads', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_yolo_track_id'), ['yolo_track_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('schedule_start', sa.String(), nullable=True),
    sa.Column('schedule_end', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('loitering_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('plate_text_raw', sa.String(), nullable=True),
    sa.Column('plate_text_normalized', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('reads_count', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_bbox', sa.JSON(), nullable=True),
    sa.Column('plate_bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plates_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plates_plate_text_normalized'), ['plate_text_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_plates_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_plates_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plates_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('watchlist_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('detection_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('correlation_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_alerts_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_alerts_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_notes')
    with op.batch_alter_table('incident_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_incident_alerts_alert_id'))

    op.drop_table('incident_alerts')
    op.drop_table('evidence')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))

    op.drop_table('incidents')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_risk_score'))
        batch_op.drop_index(batch_op.f('ix_alerts_camera_id'))

    op.drop_table('alerts')
    op.drop_table('watchlist_entries')
    with op.batch_alter_table('plates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plates_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_plates_track_id'))
        batch_op.drop_index(batch_op.f('ix_plates_timestamp'))
        batch_op.drop_index(batch_op.f('ix_plates_plate_text_normalized'))
        batch_op.drop_index(batch_op.f('ix_plates_camera_id'))

    op.drop_table('plates')
    op.drop_table('audit_logs')
    op.drop_table('alert_rules')
    op.drop_table('zones')
    op.drop_table('users')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_yolo_track_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_camera_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('self_heal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_self_heal_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_self_heal_events_component'))
        batch_op.drop_index(batch_op.f('ix_self_heal_events_camera_id'))

    op.drop_table('self_heal_events')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_track_id'))
        batch_op.drop_index(batch_op.f('ix_detections_timestamp'))
        batch_op.drop_index(batch_op.f('ix_detections_camera_id'))

    op.drop_table('detections')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_plate_text'))
        batch_op.drop_index(batch_op.f('ix_vehicles_last_seen'))

    op.drop_table('vehicles')
    op.drop_table('roles')
    op.drop_table('persons')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_external_catalog_id'))

    op.drop_table('cameras')
    # ### end Alembic commands ###
