"""PostGIS geography point per camera (PostgreSQL only).

Adds cameras.geog, generated from lat/lng (NULL for 0,0 = unknown), with a
GiST index, so nearby cameras is one indexed ST_DWithin (app/geo.py).

Generated by the DB, never written by the app, so it's not on the ORM and
alembic/env.py excludes it from drift checks. No-op on SQLite and on
PostgreSQL without PostGIS; app/geo.py falls back to haversine.

Revision ID: 5b1d7e3a9c20
Revises: 3f8a2c9d7e14
Create Date: 2026-09-28 07:00:00.000000
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '5b1d7e3a9c20'
down_revision: Union[str, None] = '3f8a2c9d7e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _postgis_available() -> bool:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return False
    return bind.execute(sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'postgis'")).first() is not None


def upgrade() -> None:
    if not _postgis_available():
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute(
        "ALTER TABLE cameras ADD COLUMN geog geography(Point, 4326) GENERATED ALWAYS AS ("
        "CASE WHEN lat IS NULL OR lng IS NULL OR (lat = 0 AND lng = 0) THEN NULL "
        "ELSE ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography END) STORED"
    )
    op.execute("CREATE INDEX ix_cameras_geog ON cameras USING GIST (geog)")


def downgrade() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute("DROP INDEX IF EXISTS ix_cameras_geog")
    op.execute("ALTER TABLE cameras DROP COLUMN IF EXISTS geog")
    # The extension is left installed: dropping it is a server-level decision
    # and would fail if anything else in the database uses it.
